# Generated by Django 6.1 on 2026-09-11 11:02

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_impactitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='mission_body',
            field=wagtail.fields.RichTextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit...'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_title',
            field=models.CharField(default='More About Our Mission', max_length=255),
        ),
    ]
