# Generated by Django 6.1 on 2026-09-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_workitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='testimonial_author',
            field=models.CharField(default='Dr. Jane Goodall, Primatologist & Anthropologist', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonial_quote',
            field=models.TextField(default="unavit's work is a beacon of hope for our planet. Their dedication to conservation is truly inspiring and I'm proud to be a supporter."),
            preserve_default=False,
        ),
    ]
