# Generated by Django 6.1 on 2026-09-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_testimonial_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='newsletter_text',
            field=models.TextField(default='Stay informed about our latest conservation efforts.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='newsletter_title',
            field=models.CharField(default='Join the Movement', max_length=255),
        ),
    ]
